site_name: Projeto base

repo_url: https://github.com/ZRafaF/ReadTheDocksBase


theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - cpp
        - md
    locale: pt_BR

docs_dir: 'docsSrc'
site_dir: 'docs'

plugins:
    - search
