site_name: Projeto base

repo_url: https://github.com/ZRafaF/ReadTheDocksBase

theme:
    name: material

    palette:
        scheme: slate
        primary: indigo
        accent: indigo

    locale: pt_BR
    features:
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky      Faz com que a navigation tab esteja sempre visivel
        - navigation.top
        - navigation.tracking
        - navigation.path
        - navigation.indexes
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        - content.code.copy


docs_dir: 'docsSrc'
site_dir: 'docs'

plugins:
    - search:
        separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
    - with-pdf:
        author: Rafael Farias
    - pdf-export

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        use_pygments: true
        auto_title: true

    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde