site_name: Projeto base

repo_url: https://github.com/ZRafaF/ReadTheDocksBase

theme:
    name: material

    palette:
        scheme: slate
        primary: pink
        accent: pink

    locale: pt_BR
    features:
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky      Faz com que a navigation tab esteja sempre visivel
        - navigation.top
        - navigation.tracking
        - navigation.path
        - navigation.indexes
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        - content.code.copy


#docs_dir: 'docsSrc'
#site_dir: 'docs'

plugins:
    - search:
        separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
    - with-pdf:
        author: Rafael Farias
        toc_title: Tabela de conteúdos
        #two_columns_level: 3
        #custom_template_path: docs/styles.scss
    - pdf-export

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        use_pygments: true      # Renderiza todos os códigos durante a build ao inves de no runtime
        auto_title: true

    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde

nav:
    - Home: index.md
    - Setup:
        - Setup/Setup.md
        - Setup/Plugins.md
        - Setup/Temas.md
    - Como usar:
        - Como_usar/Como_usar.md
        - Como_usar/Deploying.md
        - Como_usar/Documentação_utilizando_MkDocs.md
        - Como_usar/Tema_MkDocs-Material.md
        - Como_usar/Utilizacao.md
